- name: group | raspberrypi | Update cgroup options
  vars:
    cmdline_path: /boot/firmware/cmdline.txt
  loop:
    - cgroup_enable=memory
    - cgroup_memory=1
  loop_control:
    loop_var: cgroup_option
  when: cgroup_option not in lookup('ansible.builtin.file', cmdline_path)
  ansible.builtin.lineinfile:
    path: "{{ cmdline_path }}"
    regexp: '^.*$'
    line: "\\1 {{ cgroup_option }}"
    backrefs: true
  notify: reboot

- name: group | raspberrypi | Flush handlers
  ansible.builtin.meta: flush_handlers
