raspberrypi:
  hosts:
    arae[0:3].local:

thinkcentre:
  hosts:
    aether.local:

storinator:
  hosts:
    tartarus.local:

kubernetes:
  children:
    storinator:
    thinkcentre:
  hosts:
    arae[2:3].local:
