- name: Reboot machine
  listen: reboot
  ansible.builtin.reboot:
    connect_timeout: 120

- name: Apply netplan changes
  listen: netplan
  changed_when: true
  notify: NetworkManager
  ansible.builtin.command: netplan apply

- name: Restart NetworkManager
  listen: NetworkManager
  ansible.builtin.service:
    name: NetworkManager.service
    enabled: true
    state: restarted
