dependencies:
  - role: servers
    vars:
      servers_admin_groups:
        - "{{ servers_admin_groups }}"
        - microk8s
      servers_firewall_zone_configs:
        - "{{ servers_firewall_zone_configs }}"
        - zone: kubernetes
          target: ACCEPT
          interfaces:
            - vxlan.calico
      servers_snap_enabled: true
      servers_snaps:
        - "{{ servers_snaps }}"
        - name: microk8s
          classic: true
          channel: latest/stable
          aliases:
            - kubectl
            - helm

collections:
  - ansible.utils
  - kubernetes.core
