raspberrypi:
  hosts:
    arae[1:4].local:

thinkcentre:
  hosts:
    aether.local:

45drives:
  hosts:
    tartarus.local:

kubernetes:
  children:
    45drives:
    thinkcentre:
  hosts:
    arae[3:4].local:
