- name: configs | Passwordless sudo
  community.general.sudoers:
    name: allow-sudo-passwordless
    group: sudo
    commands: ALL
    nopassword: true

- name: configs | Global vimrc
  ansible.builtin.copy:
    src: vimrc
    dest: /usr/share/vim/
    mode: '0644'

- name: configs | Global user defaults
  loop:
    - bash.bashrc
    - gitconfig
    - profile
    - tmux.conf
  loop_control:
    loop_var: config_file
  ansible.builtin.copy:
    src: "{{ config_file }}"
    dest: /etc/
    mode: '0644'

- name: configs | Cockpit
  loop: "{{ query('community.general.flattened', servers_cockpit_overrides) | unique }}"
  loop_control:
    loop_var: override
    label: "{{ override.name | mandatory(msg='servers_cockpit_overrides entries require a name key') }}"
  ansible.builtin.copy:
    content: "{{ override.content | mandatory(msg='servers_cockpit_overrides entries require a name key') | to_yaml }}"
    dest: "/usr/share/cockpit/{{ override.name }}/override.json"
    mode: '0644'
