- name: snap | Enable snapd
  ansible.builtin.service:
    name: snapd
    state: started
    enabled: true

- name: snap | Install
  loop: "{{ query('community.general.flattened', servers_snaps) | unique }}"
  loop_control:
    loop_var: snap
  community.general.snap: "{{ snap }}"

- name: snap | Enable
  loop: "{{ query('community.general.flattened', servers_snaps) | unique }}"
  loop_control:
    loop_var: snap
  community.general.snap:
    name: "{{ snap }}"
    state: enabled

- name: snap | Create snap aliases
  loop: "{{ query('community.general.flattened', servers_snap_aliases) | unique }}"
  loop_control:
    loop_var: snap_alias
    label: "{{ snap_alias.alias }}"
  community.general.snap_alias:
    name: "{{ snap_alias.target }}"
    alias: "{{ snap_alias.alias }}"
