- name: snap | Install # noqa: no-free-form
  community.general.snap: "{{ snap | community.general.remove_keys(target=['aliases']) }}"

- name: snap | Enable
  community.general.snap:
    name: "{{ snap.name }}"
    state: enabled

- name: snap | Create aliases
  loop: "{{ snap.aliases }}"
  loop_control:
    loop_var: alias
    label: "{{ alias }}"
  community.general.snap_alias:
    name: "{{ snap.name }}.{{ alias }}"
    alias: "{{ alias }}"
